"""bwb.validation — validation metrics, pipeline, and sensitivity analysis."""

from bwb.validation.metrics import (
    bias,
    compute_all_metrics,
    coverage,
    crps_ensemble,
    crps_mean,
    interval_score,
    kge,
    mae,
    nse,
    pbias,
    pit,
    pit_alpha_reliability,
    reliability_alpha,
    rmse,
)
from bwb.validation.pipeline import (
    CITIES,
    CROP_CYCLES,
    SOIL_DEPTHS_CM,
    ValidationConfig,
    create_validation_config,
    generate_validation_grid,
    generate_validation_report,
    run_single_validation,
    run_validation_pipeline,
    save_validation_results,
)
from bwb.validation.sensitivity import (
    SensitivityConfig,
    bootstrap_confidence_intervals,
    compute_sobol_indices,
    default_sensitivity_config,
    generate_saltelli_samples,
    run_sensitivity_analysis,
    save_sensitivity_report,
)

__all__ = [
    # metrics
    "bias",
    "compute_all_metrics",
    "coverage",
    "crps_ensemble",
    "crps_mean",
    "interval_score",
    "kge",
    "mae",
    "nse",
    "pbias",
    "pit",
    "pit_alpha_reliability",
    "reliability_alpha",
    "rmse",
    # pipeline
    "CITIES",
    "CROP_CYCLES",
    "SOIL_DEPTHS_CM",
    "ValidationConfig",
    "create_validation_config",
    "generate_validation_grid",
    "generate_validation_report",
    "run_single_validation",
    "run_validation_pipeline",
    "save_validation_results",
    # sensitivity
    "SensitivityConfig",
    "bootstrap_confidence_intervals",
    "compute_sobol_indices",
    "default_sensitivity_config",
    "generate_saltelli_samples",
    "run_sensitivity_analysis",
    "save_sensitivity_report",
]
